POST http://localhost:8080/registration
Content-Type: application/x-www-form-urlencoded

name=Pavel&login=Pavel123&password=test

###

POST http://localhost:8080/authorization
Content-Type: application/x-www-form-urlencoded

login=Pavel123&password=test

###

POST http://localhost:8080/logout

###

POST http://localhost:8080/calc
Content-Type: application/x-www-form-urlencoded

num1=10&num2=5&operand=sum

###

GET http://localhost:8080/history

###
